### ISSUE TITLE
I get requestor asking me to assign or mount https:, I don’t have that device / handler with that name.

### ISSUE THREAD

**Issue by khval** [walkero-gr/mediavault#7]
I get requestor asking me to assign or mount https:, I don’t have that device / handler with that name.

**Comment by walkero-gr** [comment]
@khval Thank you for your report. That is so weird, because it shouldn't ask you for that. Can you please give me some more information about your system? Which version of AmigaOS you have installed? Do you have Enhancer fully installed on your system? 
When exactly this happens? When you start the app or when you click on discover button or even somewhere else? How I could reproduce it? What happens if you skip it?

**Comment by khval** [comment]
Its AmigaAmp that asks for http:, maybe I have too old AmigaAMP installed.

**Comment by khval** [comment]
Yes, its my fault, old AmigaAMP, now upgraded.

**Comment by walkero-gr** [comment]
Thanks for clearing this up.
